# Generated by Django 4.2.7 on 2023-11-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productoName', models.CharField(max_length=200)),
                ('productoDescription', models.CharField(blank=True, max_length=200)),
                ('productoPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productoImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('productoCantidad', models.PositiveBigIntegerField(default=0)),
                ('productoCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorias')),
            ],
        ),
    ]
